export const SCHEMES = {
  hippo: {
    id: 'hippo',
    name: 'Sistema Hipopótamo',
    short: 'Hipopótamo',
    eyebrow: 'Elasticidad y contragolpe',
    description: 'Clasifica el centro, decide entre Hipopótamo completo o semi-Hippo y elige la transformación o ruptura exacta sin piloto automático.',
    glyph: '♞',
    accent: '#5ed6c0',
    boardLight: '#e8edcf',
    boardDark: '#6f8f72',
    canonical: 'Funciona con ambos colores',
    plans: ['Diez hitos y doble fianchetto', 'Cuatro rutas de seguridad del rey', 'Seis rupturas: …d5, …e5, …g5, …f5, …c5 y …b5'],
  },
  london: {
    id: 'london',
    name: 'Sistema Londres',
    short: 'Londres',
    eyebrow: 'Presión y estructura',
    description: 'Desarrollo compacto con el alfil fuera de la cadena y ataque temático sobre el flanco de rey.',
    glyph: '♝',
    accent: '#ffb85c',
    boardLight: '#eeeed2',
    boardDark: '#769656',
    canonical: 'Canónico con blancas',
    plans: ['Alfil en f4', 'Triángulo d4–e3–c3', 'Ne5 y ataque al rey'],
  },
  colle: {
    id: 'colle',
    name: 'Sistema Colle',
    short: 'Colle',
    eyebrow: 'Preparar y liberar',
    description: 'Construye una posición sólida y concentra energía hasta ejecutar la ruptura central e4.',
    glyph: '♙',
    accent: '#bf9cff',
    boardLight: '#dee5eb',
    boardDark: '#6885a6',
    canonical: 'Canónico con blancas',
    plans: ['Bd3 y Nbd2', 'Preparación de e4', 'Ataque tras la ruptura'],
  },
  hedgehog: {
    id: 'hedgehog',
    name: 'Sistema Erizo',
    short: 'Erizo',
    eyebrow: 'Compresión y energía latente',
    description: 'Cede espacio con una estructura sin debilidades y prepara las liberaciones …b5 o …d5.',
    glyph: '♟',
    accent: '#e08a73',
    boardLight: '#f0ddd4',
    boardDark: '#a86658',
    canonical: 'Canónico con negras',
    plans: ['Espinas a6–b6–d6–e6', 'Piezas detrás de la estructura', 'Rupturas …b5 y …d5'],
  },
  torre: {
    id: 'torre',
    name: 'Ataque Torre',
    short: 'Torre',
    eyebrow: 'Clavada y ataque armónico',
    description: 'Desarrolla Bg5 antes de cerrar la estructura y utiliza Ne5, Bd3 y e4 para presionar el rey.',
    glyph: '♗',
    accent: '#d6a56f',
    boardLight: '#f0d9b5',
    boardDark: '#b58863',
    canonical: 'Canónico con blancas',
    plans: ['Alfil en g5', 'Caballo en e5', 'Ruptura e4 y ataque al rey'],
  },
  attack150: {
    id: 'attack150',
    name: 'Ataque 150',
    short: 'Ataque 150',
    eyebrow: 'Enroques opuestos y asalto',
    description: 'Contra Pirc o Moderna: Be3, Qd2, f3 y enroque largo antes de lanzar los peones del flanco de rey.',
    glyph: '♕',
    accent: '#d78bd6',
    boardLight: '#eadff0',
    boardDark: '#8d6a9f',
    canonical: 'Ataque blanco contra Pirc/Moderna',
    plans: ['Be3 y Qd2', 'Enroque largo', 'Avalancha h4–g4–h5'],
  },
  dragon: {
    id: 'dragon',
    name: 'Siciliana Dragón',
    short: 'Dragón',
    eyebrow: 'Defensa dinámica y contragolpe',
    description: 'Estructura siciliana con …g6, …Bg7 y presión sobre la columna c antes de lanzar el contrajuego.',
    glyph: '♞',
    accent: '#66a6d9',
    boardLight: '#dce7ee',
    boardDark: '#5f7f99',
    canonical: 'Defensa negra contra 1.e4',
    plans: ['…c5 y …d6', 'Fianchetto en g7', 'Presión por la columna c'],
  },
};

export const ENGINE_PROFILE = Object.freeze({
  depth: 32,
  multiPv: 4,
  hashMb: 128,
});

export const STYLES = {
  zero: {
    id: 'zero',
    name: 'Zero',
    label: 'Zero',
    description: 'Modo defensivo y de contraataque. Prioriza profilaxis, seguridad del rey, elasticidad y planes de largo plazo antes de liberar la posición con la ruptura correcta.',
    tolerance: 18,
    accent: '#5fc7ff',
    boardLight: '#edf7ff',
    boardDark: '#69aee0',
  },
  omega: {
    id: 'omega',
    name: 'Omega',
    label: 'Omega',
    description: 'Modo hiperagresivo y táctico. Busca iniciativa, jaques, capturas, sacrificios calculados y aperturas rápidas de líneas sin abandonar la seguridad táctica.',
    tolerance: 70,
    accent: '#ef5b52',
    boardLight: '#f6dddd',
    boardDark: '#c84f4f',
  },
};

export const PIECES = {
  w: { k: '♔', q: '♕', r: '♖', b: '♗', n: '♘', p: '♙' },
  b: { k: '♚', q: '♛', r: '♜', b: '♝', n: '♞', p: '♟' },
};

export const FILES = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'];
